#@package _global_
mephisto:
  blueprint:
    subtasks_per_unit: 1
    task_source: ${task_dir}/webapp/build/bundle.js
    data_jsonl: ${task_dir}/task_config/onboarding_in_flight.jsonl
    extra_source_dir: ${task_dir}/webapp/src/static
    units_per_assignment: 1  # How many workers you want to do each assignment?
    onboarding_qualification: turn_annotations_static-${qua_id}
    annotation_buckets: ${task_dir}/task_config/annotation_buckets.json
    response_field: False
  task:
    allowed_concurrent: 1
    assignment_duration_in_seconds: 600
    max_num_concurrent_units: 0  # 0 means infinite; set this to a positive integer to limit concurrent HITs and prevent crashes
    # maximum_units_per_worker: 1
    task_description: |
      <b><h4>Task Description</h4></b>
      <br>
      Annotate turn-by-turn conversations based on the options provided.
      <br><br>
    task_name: turn_annotations_static
    task_reward: 0.3
    task_tags: "chat,conversation,annotation,turn-taking"
    task_title: "Annotating turn-taking conversation"
mturk:
  worker_blocklist_paths: null
